import Head from 'next/head'
import Image from 'next/image'
import logo from '/public/img/logo-monografis-570x112.png'
import perfil from '/public/img/douglas-tybel-perfil-2-600x600.png'
import styles from '../styles/Home.module.css'
import { useEffect, useRef } from 'react'

export default function Home() {

  const subscription = useRef()

  useEffect(() => {

    const menuItens = document.querySelectorAll("button[id^='btn']")

    const scrollToIdOnClick = event => {
        event.preventDefault()
        const to = getScrollTopByHref() 
        scrollToPosition(to)
    }   

    menuItens.forEach(item => {
        item.addEventListener('click', scrollToIdOnClick)
    })

    const scrollToPosition = to => {
        smoothScrollTo(0, to)
    }

    const getScrollTopByHref = () => {
        return subscription.current.offsetTop;
    }

    /**
     * Smooth scroll animation
     * @param {int} endX: destination x coordinate
     * @param {int} endY: destination y coordinate
     * @param {int} duration: animation duration in ms
     */
    function smoothScrollTo(endX, endY, duration) {
        const startX = window.scrollX || window.pageXOffset;
        const startY = window.scrollY || window.pageYOffset;
        const distanceX = endX - startX;
        const distanceY = endY - startY;
        const startTime = new Date().getTime();
      
        duration = typeof duration !== 'undefined' ? duration : 800;
      
        // Easing function
        const easeInOutQuart = (time, from, distance, duration) => {
            if ((time /= duration / 2) < 1) return distance / 2 * time * time * time * time + from;
            return -distance / 2 * ((time -= 2) * time * time * time - 2) + from;
        };
      
        const timer = setInterval(() => {
            const time = new Date().getTime() - startTime;
            const newX = easeInOutQuart(time, startX, distanceX, duration);
            const newY = easeInOutQuart(time, startY, distanceY, duration);
            if (time >= duration) {
                clearInterval(timer);
            }
            window.scroll(newX, newY);
        }, 1000 / 120); // 60 fps
    };

    const form = document.querySelector('#form')
    form.addEventListener('submit', () => {
      window.location.href = "/obrigado";
    })


  }, [])

  return (
    <>

      <Head>
        <title>Monografis - Semana do TCC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-monografis-128x128.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet" />
      </Head>
        
      <section className={styles.home} id='home'>
      
        <div>
          <Image src={logo} alt='Logo do monografis' width={250} height={50}/>
        </div>

        <h1><font className={styles.h3}>Workshop Gratuito Semana do TCC</font> <font className={styles.h1}>Como Fazer Um TCC 23x Mais Rápido</font></h1>
        
        <p className={styles.caption}>Nesta semana mostrarei <strong>Como fazer um Capitulo de Referencial do Inicio ao Fim</strong>. Custe o que custar! </p>

        <button className={styles.btn} id='btn1'>QUERO RESERVAR MEU LUGAR!</button>

      </section>

      <section className={styles.content}>

        <h2><font className={styles.what}>O Que Você</font> <font className={styles.learn}>Vai Aprender Nesta Semana:</font></h2>

        <ul>
          <li>
            <h3>Os Erros comuns no inicio do TCC</h3>
            <p>Mostro os erros mais comuns do TCC cometidos pela maioria dos estudantes</p>
          </li>
          <li>
            <h3>Como focar apenas no que dá resultado</h3>
            <p>Vou te ensinar como poupar tempo e buscar conteúdo mais rápido pro seu TCC</p>
          </li>
          <li>
            <h3>Como usar Ferramentas que aceleram o TCC</h3>
            <p>Vou te mostrar as melhores Ferramentas para TCC</p>
          </li>
        </ul>

        <button className={styles.btn} id='btn2'>QUERO PARTICIPAR DA SEMANA DO TCC!</button>
        
      </section>
      
      <section className={styles.about}>

        <div>
          <Image src={perfil} alt='Douglas Tybel' width={250} height={250}/>
        </div>

        <h2>Sobre Douglas Tybel</h2>

        <p>Analista de Sistemas pela Faculdade Vale do Cricaré (2006). Pós-Graduado em Engenharia de Softwares (2008), Pós-Graduado em Docência no ensino superior.</p> 
          
        <p>Professor na Faculdade FVC, também atua como Sócio Proprietário da Efetiva Serviços e Fundador do Maior Canal sobre TCC do Youtube - Guia da Monografia com mais de 2 Milhões de visualizações.</p> 
          
        <p>Idealizador do Projeto Inovador; O Monografis Um Software Orientador de TCC nunca criado no Brasil ou exterior, que ajudou mais de 21 Mil alunos em todo Brasil a se formarem com notas maiores que 8.5 e 9.</p>

        <button className={styles.btn} id='btn3'>QUERO RESERVAR MEU LUGAR!</button>
      
      </section>
      
      <section className={styles.subscription} ref={subscription}>

        <p>Preencha os campos abaixo para participar do Workshop Gratuito, receber emails informativos e promocionais:</p>

        <form action="https://paginas.rocks/Pages/Index/29041" method="POST" id='form' className="ng-pristine ng-valid" klickart-email-subscription-form="" klickart-form-email-service-setting-id="205327" target='contato' /* novalidate="novalidate" */> 
        
          <input type="text" id='name' className="general-input" placeholder="Seu nome" name="name" email-service-value="name" klickart-edit-not-highlight="" data-klickart-form-autofill-options="{&quot;parameter&quot;:&quot;name&quot;}" klickart-edit-placeholder-id="k1h8j9iw" aria-required="true" required />
          
          <input type="text" id='email' className="general-input" placeholder="Seu melhor e-mail" name="email" email-service-value="email" klickart-edit-not-highlight="" data-klickart-form-autofill-options="{&quot;parameter&quot;:&quot;email&quot;}" klickart-edit-placeholder-id="k1h8jiyv" aria-required="true" required />

          <button className={styles.btn}>QUERO ME INSCREVER AGORA!</button>
      
          <div className="klickart-import-form-container"> 
            <input type="hidden" name="id" value="29041"/>
            <input type="hidden" name="pid" value="6088987"/>
            <input type="hidden" name="list_id" value="29041"/>
            <input type="hidden" name="provider" value="leadlovers"/>
            <input type="hidden" name="source" value=""/>
          </div>

        </form>

        <p className={styles.secure}><span className="material-icons-outlined">&#xe897;</span>Suas informações estão seguras.</p>
      </section>

      <iframe style={ {display: 'none'} } name="contato"></iframe>
   
    </>
  )
}
